# Generated by Django 4.1.7 on 2023-10-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registermodel',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
